### ISSUE TITLE
Naming of the GitHub/PyEED/...  tree

### ISSUE THREAD

**Issue by itbjpl** [PyEED/pyeed#14]
The naming of the structure of our PyEED repository is confusing. The path  https://github.com/PyEED/pyeed/tree/main/pyEED/core
contains three times "pyeed". At the highest level (https://github.com/PyEED), it is clear that "PyEED" means the PyEED project. But the meaning of pyeed on the other levels in not self-explaining. Any suggestions for an unequivocal naming of the different levels?

We might also try to visualize the different layers (Workflow - Utility fuctions - data model) to explain the PyEED concept.
[PyEED structure.pdf](https://github.com/PyEED/pyeed/files/12936869/PyEED.structure.pdf)

**Comment by haeussma** [comment]
We could change the name from the `pyeed` repo, which contains the library, to `pyeed-lib`

**Comment by torogi94** [comment]
For now, I think going with `pyeed-lib` is the right call to avoid confusion.  

Still, in the future we could think about the `PyEED` (brand) name some more and maybe search for one less ambiguous – either for the institution, the library, or both, while still keeping `PyEED` as the term for the concept (similarly to `sdRDM`).
