### ISSUE TITLE
Inconclusive definition of `Equivalence` in the data model

### ISSUE THREAD

**Issue by haeussma** [PyEED/pyeed#8]
What is the meaning of [Equivalence](https://github.com/PyEED/pyeed/blob/main/specifications/model.md#equivalence) in the data model? I think the description of the object and the object itself should be refactored.

**Comment by torogi94** [comment]
I suggest removing the object altogether

**Comment by haeussma** [comment]
Sounds good!

**Comment by torogi94** [comment]
Removed in #12
