### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by AlexWindels** [PyEED/pyeed#9]
I got the following error when running the installation line (see image). I believe it is fatal because I can't run the beta-lactamase example as suggested in the README file. I was wondering if the issue is general or related to my environment?

<img width="1137" alt="image" src="https://github.com/PyEED/pyeed/assets/72694200/08f445ee-75ce-461d-b8ee-382541cb08be">

**Comment by haeussma** [comment]
I updated the dependencies of `sdrdm_database`, should now be installable again.
